// Descripciones y categorías de funciones (nombres en español, motor HyperFormula)
// Formato: NOMBRE: [categoría, descripción]
const FX_INFO = {
  // ===== Matemáticas y trigonometría =====
  'ABS': ['Matemáticas y trigonometría', 'Devuelve el valor absoluto de un número.'],
  'ACOS': ['Matemáticas y trigonometría', 'Devuelve el arcocoseno de un número.'],
  'ACOSH': ['Matemáticas y trigonometría', 'Devuelve el coseno hiperbólico inverso de un número.'],
  'ACOT': ['Matemáticas y trigonometría', 'Devuelve la arco cotangente de un número.'],
  'ACOTH': ['Matemáticas y trigonometría', 'Devuelve la arco cotangente hiperbólica de un número.'],
  'ALEATORIO': ['Matemáticas y trigonometría', 'Devuelve un número aleatorio entre 0 y 1.'],
  'ALEATORIO.ENTRE': ['Matemáticas y trigonometría', 'Devuelve un número aleatorio entre los números que especifique.'],
  'ARABIC': ['Matemáticas y trigonometría', 'Convierte un número romano en arábigo.'],
  'ASENO': ['Matemáticas y trigonometría', 'Devuelve el arcoseno de un número.'],
  'ASENOH': ['Matemáticas y trigonometría', 'Devuelve el seno hiperbólico inverso de un número.'],
  'ATAN': ['Matemáticas y trigonometría', 'Devuelve la arcotangente de un número.'],
  'ATAN2': ['Matemáticas y trigonometría', 'Devuelve la arcotangente de las coordenadas "x" e "y".'],
  'ATANH': ['Matemáticas y trigonometría', 'Devuelve la tangente hiperbólica inversa de un número.'],
  'BASE': ['Matemáticas y trigonometría', 'Convierte un número en una representación de texto con la base dada.'],
  'CEILING.MATH': ['Matemáticas y trigonometría', 'Redondea un número hacia arriba al entero o múltiplo significativo más cercano.'],
  'CEILING.PRECISE': ['Matemáticas y trigonometría', 'Redondea un número hacia arriba al múltiplo significativo más cercano, sin importar el signo.'],
  'COCIENTE': ['Matemáticas y trigonometría', 'Devuelve la parte entera de una división.'],
  'COMBINA': ['Matemáticas y trigonometría', 'Devuelve la cantidad de combinaciones con repeticiones de una cantidad determinada de elementos.'],
  'COMBINAT': ['Matemáticas y trigonometría', 'Devuelve la cantidad de combinaciones de una cantidad determinada de objetos.'],
  'CONV.DECIMAL': ['Matemáticas y trigonometría', 'Convierte una representación de texto de un número con una base dada en un número decimal.'],
  'COS': ['Matemáticas y trigonometría', 'Devuelve el coseno de un número.'],
  'COSH': ['Matemáticas y trigonometría', 'Devuelve el coseno hiperbólico de un número.'],
  'COT': ['Matemáticas y trigonometría', 'Devuelve la cotangente de un ángulo.'],
  'COTH': ['Matemáticas y trigonometría', 'Devuelve la cotangente hiperbólica de un número.'],
  'CSC': ['Matemáticas y trigonometría', 'Devuelve la cosecante de un ángulo.'],
  'CSCH': ['Matemáticas y trigonometría', 'Devuelve la cosecante hiperbólica de un ángulo.'],
  'ENTERO': ['Matemáticas y trigonometría', 'Redondea un número hacia abajo hasta el número entero más cercano.'],
  'EXP': ['Matemáticas y trigonometría', 'Devuelve e elevado a la potencia de un número dado.'],
  'FACT': ['Matemáticas y trigonometría', 'Devuelve el factorial de un número.'],
  'FACT.DOBLE': ['Matemáticas y trigonometría', 'Devuelve el factorial doble de un número.'],
  'FLOOR.MATH': ['Matemáticas y trigonometría', 'Redondea un número hacia abajo al entero o múltiplo significativo más cercano.'],
  'FLOOR.PRECISE': ['Matemáticas y trigonometría', 'Redondea un número hacia abajo al múltiplo significativo más cercano, sin importar el signo.'],
  'GRADOS': ['Matemáticas y trigonometría', 'Convierte radianes en grados.'],
  'ISO.CEILING': ['Matemáticas y trigonometría', 'Redondea un número hacia arriba al entero o múltiplo significativo más cercano.'],
  'LN': ['Matemáticas y trigonometría', 'Devuelve el logaritmo natural de un número.'],
  'LOG': ['Matemáticas y trigonometría', 'Devuelve el logaritmo de un número en una base especificada.'],
  'LOG10': ['Matemáticas y trigonometría', 'Devuelve el logaritmo en base 10 de un número.'],
  'M.C.D': ['Matemáticas y trigonometría', 'Devuelve el máximo común divisor.'],
  'M.C.M': ['Matemáticas y trigonometría', 'Devuelve el mínimo común múltiplo.'],
  'MMULT': ['Matemáticas y trigonometría', 'Devuelve el producto matricial de dos matrices.'],
  'MULTINOMIAL': ['Matemáticas y trigonometría', 'Devuelve el polinomio de un conjunto de números.'],
  'MULTIPLO.INFERIOR': ['Matemáticas y trigonometría', 'Redondea un número hacia abajo, hacia el cero.'],
  'MULTIPLO.SUPERIOR': ['Matemáticas y trigonometría', 'Redondea un número al entero o al múltiplo significativo más cercano.'],
  'NUMERO.ROMANO': ['Matemáticas y trigonometría', 'Convierte un número arábigo en número romano con formato de texto.'],
  'PI': ['Matemáticas y trigonometría', 'Devuelve el valor de pi.'],
  'POTENCIA': ['Matemáticas y trigonometría', 'Devuelve el resultado de elevar un número a una potencia.'],
  'PRODUCTO': ['Matemáticas y trigonometría', 'Multiplica sus argumentos.'],
  'RADIANES': ['Matemáticas y trigonometría', 'Convierte grados en radianes.'],
  'RAIZ': ['Matemáticas y trigonometría', 'Devuelve una raíz cuadrada positiva.'],
  'RAIZ2PI': ['Matemáticas y trigonometría', 'Devuelve la raíz cuadrada de un número multiplicado por PI.'],
  'REDOND.MULT': ['Matemáticas y trigonometría', 'Devuelve un número redondeado al múltiplo deseado.'],
  'REDONDEA.IMPAR': ['Matemáticas y trigonometría', 'Redondea un número hasta el entero impar más próximo.'],
  'REDONDEA.PAR': ['Matemáticas y trigonometría', 'Redondea un número hasta el entero par más próximo.'],
  'REDONDEAR': ['Matemáticas y trigonometría', 'Redondea un número al número de decimales especificado.'],
  'REDONDEAR.MAS': ['Matemáticas y trigonometría', 'Redondea un número hacia arriba, en dirección contraria a cero.'],
  'REDONDEAR.MENOS': ['Matemáticas y trigonometría', 'Redondea un número hacia abajo, hacia el cero.'],
  'RESIDUO': ['Matemáticas y trigonometría', 'Devuelve el resto de la división.'],
  'SEC': ['Matemáticas y trigonometría', 'Devuelve la secante de un ángulo.'],
  'SECH': ['Matemáticas y trigonometría', 'Devuelve la secante hiperbólica de un ángulo.'],
  'SECUENCIA': ['Matemáticas y trigonometría', 'Genera una lista de números secuenciales en una matriz, como 1, 2, 3, 4.'],
  'SENO': ['Matemáticas y trigonometría', 'Devuelve el seno del ángulo especificado.'],
  'SENOH': ['Matemáticas y trigonometría', 'Devuelve el seno hiperbólico de un número.'],
  'SIGNO': ['Matemáticas y trigonometría', 'Devuelve el signo de un número.'],
  'SUBTOTALES': ['Matemáticas y trigonometría', 'Devuelve un subtotal en una lista o base de datos.'],
  'SUMA': ['Matemáticas y trigonometría', 'Suma sus argumentos.'],
  'SUMA.CUADRADOS': ['Matemáticas y trigonometría', 'Devuelve la suma de los cuadrados de los argumentos.'],
  'SUMA.SERIES': ['Matemáticas y trigonometría', 'Devuelve la suma de una serie de potencias en función de la fórmula.'],
  'SUMAPRODUCTO': ['Matemáticas y trigonometría', 'Devuelve la suma de los productos de los correspondientes componentes de matriz.'],
  'SUMAR.SI': ['Matemáticas y trigonometría', 'Suma las celdas del rango que cumplen los criterios especificados.'],
  'SUMAR.SI.CONJUNTO': ['Matemáticas y trigonometría', 'Suma las celdas de un rango que cumplen varios criterios.'],
  'SUMAX2MASY2': ['Matemáticas y trigonometría', 'Devuelve la suma de la suma de los cuadrados de los valores correspondientes de dos matrices.'],
  'SUMAX2MENOSY2': ['Matemáticas y trigonometría', 'Devuelve la suma de la diferencia de los cuadrados de los valores correspondientes de dos matrices.'],
  'SUMAXMENOSY2': ['Matemáticas y trigonometría', 'Devuelve la suma de los cuadrados de las diferencias de los valores correspondientes de dos matrices.'],
  'TAN': ['Matemáticas y trigonometría', 'Devuelve la tangente de un número.'],
  'TANH': ['Matemáticas y trigonometría', 'Devuelve la tangente hiperbólica de un número.'],
  'TRANSPONER': ['Matemáticas y trigonometría', 'Devuelve la transposición de una matriz.'],
  'TRUNCAR': ['Matemáticas y trigonometría', 'Trunca un número a un entero.'],

  // ===== Lógica =====
  'FALSO': ['Lógica', 'Devuelve el valor lógico FALSO.'],
  'NO': ['Lógica', 'Invierte el valor lógico del argumento.'],
  'O': ['Lógica', 'Devuelve VERDADERO si cualquier argumento es VERDADERO.'],
  'SI': ['Lógica', 'Especifica una prueba lógica que realizar. =SI(prueba; valor_si_verdadero; valor_si_falso)'],
  'SI.CONJUNTO': ['Lógica', 'Comprueba una o varias condiciones y devuelve el valor de la primera condición VERDADERA.'],
  'SI.ERROR': ['Lógica', 'Devuelve un valor si la fórmula da error; de lo contrario, el resultado de la fórmula.'],
  'IFNA': ['Lógica', 'Devuelve el valor que se especifica si la expresión da #N/A; si no, el resultado de la expresión.'],
  'VERDADERO': ['Lógica', 'Devuelve el valor lógico VERDADERO.'],
  'XOR': ['Lógica', 'Devuelve un O exclusivo lógico de todos los argumentos.'],
  'Y': ['Lógica', 'Devuelve VERDADERO si todos sus argumentos son VERDADERO.'],

  // ===== Texto =====
  'CARACTER': ['Texto', 'Devuelve el carácter especificado por el número de código.'],
  'CODIGO': ['Texto', 'Devuelve un código numérico del primer carácter de una cadena de texto.'],
  'CONCATENAR': ['Texto', 'Concatena varios elementos de texto en uno solo.'],
  'DERECHA': ['Texto', 'Devuelve los caracteres del lado derecho de un valor de texto.'],
  'ENCONTRAR': ['Texto', 'Busca un valor de texto dentro de otro (distingue mayúsculas de minúsculas).'],
  'ESPACIOS': ['Texto', 'Quita los espacios del texto.'],
  'EXTRAE': ['Texto', 'Devuelve un número específico de caracteres de una cadena de texto, comenzando en la posición especificada.'],
  'HALLAR': ['Texto', 'Busca un valor de texto dentro de otro (no distingue mayúsculas de minúsculas).'],
  'IGUAL': ['Texto', 'Comprueba si dos valores de texto son idénticos.'],
  'IZQUIERDA': ['Texto', 'Devuelve los caracteres del lado izquierdo de un valor de texto.'],
  'LARGO': ['Texto', 'Devuelve el número de caracteres de una cadena de texto.'],
  'LIMPIAR': ['Texto', 'Quita del texto todos los caracteres no imprimibles.'],
  'MAYUSC': ['Texto', 'Pone el texto en mayúsculas.'],
  'MINUSC': ['Texto', 'Pone el texto en minúsculas.'],
  'MONEDA.DEC': ['Finanzas', 'Convierte un precio expresado como fracción en un precio expresado como número decimal.'],
  'MONEDA.FRAC': ['Finanzas', 'Convierte un precio expresado como número decimal en un precio expresado como fracción.'],
  'NOMPROPIO': ['Texto', 'Pone en mayúscula la primera letra de cada palabra de un valor de texto.'],
  'REEMPLAZAR': ['Texto', 'Reemplaza caracteres de texto.'],
  'REPETIR': ['Texto', 'Repite el texto un número determinado de veces.'],
  'SPLIT': ['Texto', 'Divide una cadena de texto usando un delimitador.'],
  'SUSTITUIR': ['Texto', 'Sustituye texto nuevo por texto antiguo en una cadena de texto.'],
  'T': ['Texto', 'Convierte sus argumentos a texto.'],
  'TEXTO': ['Texto', 'Da formato a un número y lo convierte en texto.'],
  'UNICHAR': ['Texto', 'Devuelve el carácter Unicode al que hace referencia el valor numérico dado.'],
  'UNICODE': ['Texto', 'Devuelve el número (punto de código) que corresponde al primer carácter del texto.'],
  'UNIRCADENAS': ['Texto', 'Combina el texto de varios rangos o cadenas con un delimitador.'],
  'VALOR': ['Texto', 'Convierte un argumento de texto en un número.'],

  // ===== Fecha y hora =====
  'AHORA': ['Fecha y hora', 'Devuelve el número de serie correspondiente a la fecha y hora actuales.'],
  'AÑO': ['Fecha y hora', 'Convierte un número de serie en un valor de año.'],
  'DATEDIF': ['Fecha y hora', 'Calcula el número de días, meses o años entre dos fechas.'],
  'DIA': ['Fecha y hora', 'Convierte un número de serie en un valor de día del mes.'],
  'DIA.LAB': ['Fecha y hora', 'Devuelve el número de serie de la fecha anterior o posterior a un número especificado de días laborables.'],
  'DIA.LAB.INTL': ['Fecha y hora', 'Como DIA.LAB, con parámetros para indicar cuáles y cuántos son días de fin de semana.'],
  'DIAS.LAB': ['Fecha y hora', 'Devuelve la cantidad de días laborables totales entre dos fechas.'],
  'DIAS.LAB.INTL': ['Fecha y hora', 'Como DIAS.LAB, con parámetros para indicar los días de fin de semana.'],
  'DIAS360': ['Fecha y hora', 'Calcula el número de días entre dos fechas a partir de un año de 360 días.'],
  'DIASEM': ['Fecha y hora', 'Convierte un número de serie en un valor de día de la semana.'],
  'DÍAS': ['Fecha y hora', 'Devuelve la cantidad de días entre dos fechas.'],
  'FECHA': ['Fecha y hora', 'Devuelve el número de serie correspondiente a una fecha determinada. =FECHA(año; mes; día)'],
  'FECHA.MES': ['Fecha y hora', 'Devuelve la fecha equivalente al número indicado de meses anteriores o posteriores a la fecha inicial.'],
  'FECHANUMERO': ['Fecha y hora', 'Convierte una fecha con formato de texto en un valor de número de serie.'],
  'FIN.MES': ['Fecha y hora', 'Devuelve el último día del mes anterior o posterior a un número de meses especificado.'],
  'FRAC.AÑO': ['Fecha y hora', 'Devuelve la fracción de año que representa el número total de días entre dos fechas.'],
  'HORA': ['Fecha y hora', 'Convierte un número de serie en un valor de hora.'],
  'HORANUMERO': ['Fecha y hora', 'Convierte una hora con formato de texto en un valor de número de serie.'],
  'HOY': ['Fecha y hora', 'Devuelve el número de serie correspondiente al día actual.'],
  'INTERVAL': ['Fecha y hora', 'Convierte una cantidad de segundos en un intervalo de tiempo.'],
  'ISOWEEKNUM': ['Fecha y hora', 'Devuelve el número de semana ISO del año para una fecha determinada.'],
  'MES': ['Fecha y hora', 'Convierte un número de serie en un valor de mes.'],
  'MINUTO': ['Fecha y hora', 'Convierte un número de serie en un valor de minuto.'],
  'NSHORA': ['Fecha y hora', 'Devuelve el número de serie correspondiente a una hora determinada. =NSHORA(hora; minuto; segundo)'],
  'NUM.DE.SEMANA': ['Fecha y hora', 'Convierte un número de serie en un número que representa la semana del año.'],
  'SEGUNDO': ['Fecha y hora', 'Convierte un número de serie en un valor de segundo.'],

  // ===== Búsqueda y referencia =====
  'BUSCARH': ['Búsqueda y referencia', 'Busca en la fila superior de una matriz y devuelve el valor de la celda indicada.'],
  'BUSCARV': ['Búsqueda y referencia', 'Busca en la primera columna de una matriz y devuelve el valor de una celda de la misma fila. =BUSCARV(valor; rango; columna; [ordenado])'],
  'BUSCARX': ['Búsqueda y referencia', 'Busca en un rango o matriz y devuelve el elemento correspondiente a la primera coincidencia.'],
  'COINCIDIR': ['Búsqueda y referencia', 'Busca valores de una referencia o una matriz y devuelve su posición.'],
  'COLUMNA': ['Búsqueda y referencia', 'Devuelve el número de columna de una referencia.'],
  'COLUMNAS': ['Búsqueda y referencia', 'Devuelve el número de columnas de una referencia.'],
  'DESREF': ['Búsqueda y referencia', 'Devuelve un desplazamiento de referencia respecto a una referencia dada.'],
  'DIRECCION': ['Búsqueda y referencia', 'Devuelve una referencia como texto a una sola celda de una hoja de cálculo.'],
  'ELEGIR': ['Búsqueda y referencia', 'Elige un valor de una lista de valores.'],
  'FILA': ['Búsqueda y referencia', 'Devuelve el número de fila de una referencia.'],
  'FILAS': ['Búsqueda y referencia', 'Devuelve el número de filas de una referencia.'],
  'FILTER': ['Búsqueda y referencia', 'Filtra un rango de datos en función de los criterios que defina.'],
  'FORMULATEXTO': ['Búsqueda y referencia', 'Devuelve la fórmula en la referencia dada como texto.'],
  'HIPERVINCULO': ['Búsqueda y referencia', 'Crea un vínculo a un documento o página web.'],
  'HOJA': ['Información', 'Devuelve el número de la hoja a la que se hace referencia.'],
  'HOJAS': ['Información', 'Devuelve la cantidad de hojas en una referencia.'],
  'INDICE': ['Búsqueda y referencia', 'Usa un índice para elegir un valor de una referencia o matriz.'],

  // ===== Información =====
  'ES.IMPAR': ['Información', 'Devuelve VERDADERO si el número es impar.'],
  'ES.PAR': ['Información', 'Devuelve VERDADERO si el número es par.'],
  'ESBLANCO': ['Información', 'Devuelve VERDADERO si el valor está en blanco.'],
  'ESERR': ['Información', 'Devuelve VERDADERO si el valor es cualquier valor de error excepto #N/A.'],
  'ESERROR': ['Información', 'Devuelve VERDADERO si el valor es cualquier valor de error.'],
  'ESLOGICO': ['Información', 'Devuelve VERDADERO si el valor es un valor lógico.'],
  'ESNOD': ['Información', 'Devuelve VERDADERO si el valor es el valor de error #N/A.'],
  'ESNOTEXTO': ['Información', 'Devuelve VERDADERO si el valor no es texto.'],
  'ESNUMERO': ['Información', 'Devuelve VERDADERO si el valor es un número.'],
  'ESREF': ['Información', 'Devuelve VERDADERO si el valor es una referencia.'],
  'ESTEXTO': ['Información', 'Devuelve VERDADERO si el valor es texto.'],
  'ISBINARY': ['Información', 'Devuelve VERDADERO si el valor es un número binario.'],
  'ISFORMULA': ['Información', 'Devuelve VERDADERO si la celda referida contiene una fórmula.'],
  'N': ['Información', 'Devuelve un valor convertido en un número.'],
  'NOD': ['Información', 'Devuelve el valor de error #N/A.'],

  // ===== Estadística =====
  'COEF.DE.CORREL': ['Estadística', 'Devuelve el coeficiente de correlación entre dos conjuntos de datos.'],
  'COEFICIENTE.ASIMETRIA': ['Estadística', 'Devuelve la asimetría de una distribución.'],
  'COEFICIENTE.R2': ['Estadística', 'Devuelve el cuadrado del coeficiente de correlación de Pearson.'],
  'CONTAR': ['Estadística', 'Cuenta cuántos números hay en la lista de argumentos.'],
  'CONTAR.BLANCO': ['Estadística', 'Cuenta el número de celdas en blanco de un rango.'],
  'CONTAR.SI': ['Estadística', 'Cuenta las celdas del rango que cumplen el criterio especificado.'],
  'CONTAR.SI.CONJUNTO': ['Estadística', 'Cuenta las celdas del rango que cumplen varios criterios.'],
  'CONTARA': ['Estadística', 'Cuenta cuántos valores hay en la lista de argumentos.'],
  'COUNTUNIQUE': ['Estadística', 'Cuenta la cantidad de valores únicos en una lista.'],
  'COVAR': ['Estadística', 'Devuelve la covarianza, promedio de los productos de las desviaciones por pares.'],
  'COVARIANZA.M': ['Estadística', 'Devuelve la covarianza de una muestra.'],
  'CUARTIL': ['Estadística', 'Devuelve el cuartil de un conjunto de datos.'],
  'CUARTIL.EXC': ['Estadística', 'Devuelve el cuartil del conjunto de datos (percentiles de 0 a 1, exclusivo).'],
  'CUARTIL.INC': ['Estadística', 'Devuelve el cuartil de un conjunto de datos.'],
  'DESVEST': ['Estadística', 'Calcula la desviación estándar a partir de una muestra.'],
  'DESVEST.M': ['Estadística', 'Calcula la desviación estándar a partir de una muestra.'],
  'DESVEST.P': ['Estadística', 'Calcula la desviación estándar en función de toda la población.'],
  'DESVESTA': ['Estadística', 'Desviación estándar de una muestra, incluidos números, texto y valores lógicos.'],
  'DESVESTP': ['Estadística', 'Calcula la desviación estándar en función de toda la población.'],
  'DESVESTPA': ['Estadística', 'Desviación estándar de la población, incluidos números, texto y valores lógicos.'],
  'DESVIA2': ['Estadística', 'Devuelve la suma de los cuadrados de las desviaciones.'],
  'DESVPROM': ['Estadística', 'Devuelve el promedio de las desviaciones absolutas de la media de los puntos de datos.'],
  'ERROR.TIPICO.XY': ['Estadística', 'Devuelve el error estándar del valor de "y" previsto para cada "x" de la regresión.'],
  'FISHER': ['Estadística', 'Devuelve la transformación Fisher.'],
  'GAMMA': ['Estadística', 'Devuelve el valor de la función Gamma.'],
  'GAMMA.LN': ['Estadística', 'Devuelve el logaritmo natural de la función gamma, G(x).'],
  'GAMMA.LN.EXACTO': ['Estadística', 'Devuelve el logaritmo natural de la función gamma, G(x).'],
  'GAUSS': ['Estadística', 'Devuelve un 0,5 menos que la distribución acumulativa normal estándar.'],
  'K.ESIMO.MAYOR': ['Estadística', 'Devuelve el k-ésimo mayor valor de un conjunto de datos.'],
  'K.ESIMO.MENOR': ['Estadística', 'Devuelve el k-ésimo menor valor de un conjunto de datos.'],
  'MAX': ['Estadística', 'Devuelve el valor máximo de una lista de argumentos.'],
  'MAX.SI.CONJUNTO': ['Estadística', 'Devuelve el valor máximo entre celdas según un conjunto de condiciones o criterios.'],
  'MAXA': ['Estadística', 'Devuelve el valor máximo, incluidos números, texto y valores lógicos.'],
  'MEDIA.ARMO': ['Estadística', 'Devuelve la media armónica.'],
  'MEDIA.GEOM': ['Estadística', 'Devuelve la media geométrica.'],
  'MEDIANA': ['Estadística', 'Devuelve la mediana de los números dados.'],
  'MIN': ['Estadística', 'Devuelve el valor mínimo de una lista de argumentos.'],
  'MIN.SI.CONJUNTO': ['Estadística', 'Devuelve el valor mínimo entre celdas según un conjunto de condiciones o criterios.'],
  'MINA': ['Estadística', 'Devuelve el valor mínimo, incluidos números, texto y valores lógicos.'],
  'NORMALIZACION': ['Estadística', 'Devuelve un valor normalizado.'],
  'PEARSON': ['Estadística', 'Devuelve el coeficiente de momento de correlación de producto Pearson.'],
  'PENDIENTE': ['Estadística', 'Devuelve la pendiente de la línea de regresión lineal.'],
  'PERCENTIL': ['Estadística', 'Devuelve el k-ésimo percentil de los valores de un rango.'],
  'PERCENTIL.EXC': ['Estadística', 'Devuelve el k-ésimo percentil (k entre 0 y 1, exclusivo).'],
  'PERCENTIL.INC': ['Estadística', 'Devuelve el k-ésimo percentil de los valores de un rango.'],
  'PHI': ['Estadística', 'Devuelve el valor de la función de densidad para una distribución normal estándar.'],
  'PROMEDIO': ['Estadística', 'Devuelve el promedio de sus argumentos.'],
  'PROMEDIO.SI': ['Estadística', 'Devuelve el promedio de las celdas de un rango que cumplen unos criterios determinados.'],
  'PROMEDIOA': ['Estadística', 'Devuelve el promedio de sus argumentos, incluidos números, texto y valores lógicos.'],
  'VAR': ['Estadística', 'Calcula la varianza de una muestra.'],
  'VAR.P': ['Estadística', 'Calcula la varianza en función de toda la población.'],
  'VAR.S': ['Estadística', 'Calcula la varianza de una muestra.'],
  'VARA': ['Estadística', 'Varianza de una muestra, incluidos números, texto y valores lógicos.'],
  'VARP': ['Estadística', 'Calcula la varianza en función de toda la población.'],
  'VARPA': ['Estadística', 'Varianza de la población, incluidos números, texto y valores lógicos.'],

  // ===== Distribuciones estadísticas =====
  'DISTR.BETA': ['Estadística', 'Devuelve la función de distribución beta acumulativa.'],
  'DISTR.BETA.INV': ['Estadística', 'Devuelve la función inversa de la distribución beta.'],
  'DISTR.BETA.N': ['Estadística', 'Devuelve la función de distribución beta acumulativa.'],
  'DISTR.BINOM': ['Estadística', 'Devuelve la probabilidad de una variable aleatoria discreta siguiendo una distribución binomial.'],
  'DISTR.BINOM.N': ['Estadística', 'Devuelve la probabilidad de una variable aleatoria discreta siguiendo una distribución binomial.'],
  'BINOM.CRIT': ['Estadística', 'Devuelve el menor valor cuya distribución binomial acumulativa es menor o igual a un criterio.'],
  'INV.BINOM': ['Estadística', 'Devuelve el menor valor cuya distribución binomial acumulativa es menor o igual a un criterio.'],
  'DISTR.CHI': ['Estadística', 'Devuelve la probabilidad de una cola de distribución chi cuadrado.'],
  'DISTR.CHICUAD': ['Estadística', 'Devuelve la función de densidad de la distribución chi cuadrado.'],
  'DISTR.CHICUAD.CD': ['Estadística', 'Devuelve la probabilidad de una cola derecha de la distribución chi cuadrado.'],
  'INV.CHICUAD': ['Estadística', 'Devuelve la función inversa de la distribución chi cuadrado.'],
  'INV.CHICUAD.CD': ['Estadística', 'Devuelve la inversa de la probabilidad de cola derecha de la distribución chi cuadrado.'],
  'PRUEBA.CHI': ['Estadística', 'Devuelve la prueba de independencia.'],
  'PRUEBA.CHI.INV': ['Estadística', 'Devuelve la inversa de la probabilidad de una cola de la distribución chi cuadrado.'],
  'PRUEBA.CHICUAD': ['Estadística', 'Devuelve la prueba de independencia.'],
  'DISTR.EXP': ['Estadística', 'Devuelve la distribución exponencial.'],
  'DISTR.EXP.N': ['Estadística', 'Devuelve la distribución exponencial.'],
  'DISTR.F': ['Estadística', 'Devuelve la distribución de probabilidad F.'],
  'DISTR.F.CD': ['Estadística', 'Devuelve la distribución de probabilidad F (cola derecha).'],
  'DISTR.F.INV': ['Estadística', 'Devuelve la función inversa de la distribución de probabilidad F.'],
  'DISTR.F.N': ['Estadística', 'Devuelve la distribución de probabilidad F.'],
  'INV.F': ['Estadística', 'Devuelve la función inversa de la distribución de probabilidad F.'],
  'INV.F.CD': ['Estadística', 'Devuelve la inversa de la distribución F (cola derecha).'],
  'PRUEBA.F': ['Estadística', 'Devuelve el resultado de una prueba F.'],
  'PRUEBA.F.N': ['Estadística', 'Devuelve el resultado de una prueba F.'],
  'PRUEBA.FISHER.INV': ['Estadística', 'Devuelve la función inversa de la transformación Fisher.'],
  'DISTR.GAMMA': ['Estadística', 'Devuelve la distribución gamma.'],
  'DISTR.GAMMA.INV': ['Estadística', 'Devuelve la función inversa de la distribución gamma acumulativa.'],
  'DISTR.GAMMA.N': ['Estadística', 'Devuelve la distribución gamma.'],
  'INV.GAMMA': ['Estadística', 'Devuelve la función inversa de la distribución gamma acumulativa.'],
  'DISTR.HIPERGEOM': ['Estadística', 'Devuelve la distribución hipergeométrica.'],
  'DISTR.HIPERGEOM.N': ['Estadística', 'Devuelve la distribución hipergeométrica.'],
  'DISTR.LOG.INV': ['Estadística', 'Devuelve la inversa de la distribución logarítmica normal acumulativa.'],
  'DISTR.LOG.NORM': ['Estadística', 'Devuelve la distribución logarítmico-normal acumulativa.'],
  'DISTR.LOGNORM': ['Estadística', 'Devuelve la distribución logarítmico-normal acumulativa.'],
  'INV.LOGNORM': ['Estadística', 'Devuelve la inversa de la distribución logarítmica normal acumulativa.'],
  'DISTR.NORM': ['Estadística', 'Devuelve la distribución normal acumulativa.'],
  'DISTR.NORM.ESTAND': ['Estadística', 'Devuelve la distribución normal estándar acumulativa.'],
  'DISTR.NORM.ESTAND.INV': ['Estadística', 'Devuelve la inversa de la distribución normal estándar acumulativa.'],
  'DISTR.NORM.ESTAND.N': ['Estadística', 'Devuelve la distribución normal estándar acumulativa.'],
  'DISTR.NORM.INV': ['Estadística', 'Devuelve la función inversa de la distribución normal acumulativa.'],
  'DISTR.NORM.N': ['Estadística', 'Devuelve la distribución normal acumulativa.'],
  'INV.NORM': ['Estadística', 'Devuelve la función inversa de la distribución normal acumulativa.'],
  'INV.NORM.ESTAND': ['Estadística', 'Devuelve la inversa de la distribución normal estándar acumulativa.'],
  'DISTR.T': ['Estadística', 'Devuelve la distribución de t de Student.'],
  'DISTR.T.2C': ['Estadística', 'Devuelve los puntos porcentuales de la distribución t de Student (dos colas).'],
  'DISTR.T.CD': ['Estadística', 'Devuelve la distribución de t de Student (cola derecha).'],
  'DISTR.T.INV': ['Estadística', 'Devuelve la función inversa de la distribución de t de Student.'],
  'DISTR.T.N': ['Estadística', 'Devuelve los puntos porcentuales de la distribución t de Student.'],
  'INV.T': ['Estadística', 'Devuelve el valor t de la distribución t de Student según probabilidad y grados de libertad.'],
  'INV.T.2C': ['Estadística', 'Devuelve la función inversa de la distribución de t de Student (dos colas).'],
  'PRUEBA.T': ['Estadística', 'Devuelve la probabilidad asociada a una prueba t de Student.'],
  'PRUEBA.T.N': ['Estadística', 'Devuelve la probabilidad asociada a una prueba t de Student.'],
  'PRUEBA.Z': ['Estadística', 'Devuelve el valor de una probabilidad de una cola de una prueba z.'],
  'PRUEBA.Z.N': ['Estadística', 'Devuelve el valor de una probabilidad de una cola de una prueba z.'],
  'DIST.WEIBULL': ['Estadística', 'Devuelve la distribución de Weibull.'],
  'DISTR.WEIBULL': ['Estadística', 'Devuelve la distribución de Weibull.'],
  'POISSON': ['Estadística', 'Devuelve la distribución de Poisson.'],
  'POISSON.DIST': ['Estadística', 'Devuelve la distribución de Poisson.'],
  'NEGBINOM.DIST': ['Estadística', 'Devuelve la distribución binomial negativa.'],
  'NEGBINOMDIST': ['Estadística', 'Devuelve la distribución binomial negativa.'],
  'INTERVALO.CONFIANZA': ['Estadística', 'Devuelve el intervalo de confianza de la media de una población.'],
  'INTERVALO.CONFIANZA.NORM': ['Estadística', 'Devuelve el intervalo de confianza de la media de una población.'],
  'INTERVALO.CONFIANZA.T': ['Estadística', 'Intervalo de confianza para la media, usando la distribución t de Student.'],
  'INV.BETA.N': ['Estadística', 'Devuelve la función inversa de la distribución beta acumulativa.'],

  // ===== Finanzas =====
  'DB': ['Finanzas', 'Devuelve la amortización de un activo con el método de amortización de saldo fijo.'],
  'DDB': ['Finanzas', 'Devuelve la amortización de un activo con el método de doble disminución de saldo.'],
  'INT.EFECTIVO': ['Finanzas', 'Devuelve la tasa de interés anual efectiva.'],
  'INT.PAGO.DIR': ['Finanzas', 'Calcula el interés pagado durante un período específico de una inversión.'],
  'LETRA.DE.TES.PRECIO': ['Finanzas', 'Devuelve el precio por 100 $ de valor nominal de una letra del Tesoro.'],
  'LETRA.DE.TES.RENDTO': ['Finanzas', 'Devuelve el rendimiento de una letra del Tesoro.'],
  'LETRA.DE.TEST.EQV.A.BONO': ['Finanzas', 'Devuelve el rendimiento de un bono equivalente a una letra del Tesoro.'],
  'NPER': ['Finanzas', 'Devuelve el número de períodos de una inversión.'],
  'PAGO': ['Finanzas', 'Devuelve el pago periódico de una anualidad. =PAGO(tasa; nper; va)'],
  'PAGO.INT.ENTRE': ['Finanzas', 'Devuelve el interés acumulado pagado entre dos períodos.'],
  'PAGO.PRINC.ENTRE': ['Finanzas', 'Devuelve el capital acumulado pagado de un préstamo entre dos períodos.'],
  'PAGOINT': ['Finanzas', 'Devuelve el pago de intereses de una inversión durante un período determinado.'],
  'PAGOPRIN': ['Finanzas', 'Devuelve el pago de capital de una inversión durante un período determinado.'],
  'PDURATION': ['Finanzas', 'Devuelve la cantidad de períodos necesarios para que una inversión alcance un valor especificado.'],
  'RRI': ['Finanzas', 'Devuelve una tasa de interés equivalente para el crecimiento de una inversión.'],
  'SLN': ['Finanzas', 'Devuelve la amortización por método directo de un activo en un período dado.'],
  'SYD': ['Finanzas', 'Devuelve la depreciación por método de anualidades de un activo durante un período especificado.'],
  'TASA': ['Finanzas', 'Devuelve la tasa de interés por período de una anualidad.'],
  'TASA.NOMINAL': ['Finanzas', 'Devuelve la tasa nominal de interés anual.'],
  'TIR': ['Finanzas', 'Devuelve la tasa interna de retorno para una serie de flujos de efectivo.'],
  'TIRM': ['Finanzas', 'Devuelve la tasa interna de retorno con flujos financiados a tasas diferentes.'],
  'VA': ['Finanzas', 'Devuelve el valor presente de una inversión.'],
  'VF': ['Finanzas', 'Devuelve el valor futuro de una inversión.'],
  'VF.PLAN': ['Finanzas', 'Devuelve el valor futuro de un capital tras aplicar una serie de tasas de interés compuesto.'],
  'VNA': ['Finanzas', 'Devuelve el valor neto actual de una inversión con flujos periódicos y una tasa de descuento.'],
  'VNA.NO.PER': ['Finanzas', 'Devuelve el valor neto actual para flujos de efectivo no periódicos.'],

  // ===== Ingeniería =====
  'BESSELI': ['Ingeniería', 'Devuelve la función Bessel In(x) modificada.'],
  'BESSELJ': ['Ingeniería', 'Devuelve la función Bessel Jn(x).'],
  'BESSELK': ['Ingeniería', 'Devuelve la función Bessel Kn(x) modificada.'],
  'BESSELY': ['Ingeniería', 'Devuelve la función Bessel Yn(x).'],
  'BIN.A.DEC': ['Ingeniería', 'Convierte un número binario en decimal.'],
  'BIN.A.HEX': ['Ingeniería', 'Convierte un número binario en hexadecimal.'],
  'BIN.A.OCT': ['Ingeniería', 'Convierte un número binario en octal.'],
  'BITAND': ['Ingeniería', 'Devuelve un Y bit a bit de dos números.'],
  'BITLSHIFT': ['Ingeniería', 'Devuelve un número desplazado a la izquierda una cantidad de bits.'],
  'BITOR': ['Ingeniería', 'Devuelve un O bit a bit de dos números.'],
  'BITRSHIFT': ['Ingeniería', 'Devuelve un número desplazado a la derecha una cantidad de bits.'],
  'BITXOR': ['Ingeniería', 'Devuelve un O exclusivo bit a bit de dos números.'],
  'COMPLEJO': ['Ingeniería', 'Convierte coeficientes reales e imaginarios en un número complejo.'],
  'DEC.A.BIN': ['Ingeniería', 'Convierte un número decimal en binario.'],
  'DEC.A.HEX': ['Ingeniería', 'Convierte un número decimal en hexadecimal.'],
  'DEC.A.OCT': ['Ingeniería', 'Convierte un número decimal en octal.'],
  'DELTA': ['Ingeniería', 'Comprueba si dos valores son iguales.'],
  'FUN.ERROR': ['Ingeniería', 'Devuelve la función de error.'],
  'FUN.ERROR.COMPL': ['Ingeniería', 'Devuelve la función de error complementaria.'],
  'HEX.A.BIN': ['Ingeniería', 'Convierte un número hexadecimal en binario.'],
  'HEX.A.DEC': ['Ingeniería', 'Convierte un número hexadecimal en decimal.'],
  'HEX.A.OCT': ['Ingeniería', 'Convierte un número hexadecimal en octal.'],
  'IM.ABS': ['Ingeniería', 'Devuelve el valor absoluto (módulo) de un número complejo.'],
  'IM.ANGULO': ['Ingeniería', 'Devuelve el argumento theta, un ángulo expresado en radianes.'],
  'IM.CONJUGADA': ['Ingeniería', 'Devuelve la conjugada compleja de un número complejo.'],
  'IM.COS': ['Ingeniería', 'Devuelve el coseno de un número complejo.'],
  'IM.DIV': ['Ingeniería', 'Devuelve el cociente de dos números complejos.'],
  'IM.EXP': ['Ingeniería', 'Devuelve el exponencial de un número complejo.'],
  'IM.LN': ['Ingeniería', 'Devuelve el logaritmo natural de un número complejo.'],
  'IM.LOG10': ['Ingeniería', 'Devuelve el logaritmo en base 10 de un número complejo.'],
  'IM.LOG2': ['Ingeniería', 'Devuelve el logaritmo en base 2 de un número complejo.'],
  'IM.POT': ['Ingeniería', 'Devuelve un número complejo elevado a una potencia entera.'],
  'IM.PRODUCT': ['Ingeniería', 'Devuelve el producto de números complejos.'],
  'IM.RAIZ2': ['Ingeniería', 'Devuelve la raíz cuadrada de un número complejo.'],
  'IM.REAL': ['Ingeniería', 'Devuelve el coeficiente real de un número complejo.'],
  'IM.SENO': ['Ingeniería', 'Devuelve el seno de un número complejo.'],
  'IM.SUM': ['Ingeniería', 'Devuelve la suma de números complejos.'],
  'IM.SUSTR': ['Ingeniería', 'Devuelve la diferencia entre dos números complejos.'],
  'IMAGINARIO': ['Ingeniería', 'Devuelve el coeficiente imaginario de un número complejo.'],
  'IMCOSH': ['Ingeniería', 'Devuelve el coseno hiperbólico de un número complejo.'],
  'IMCOT': ['Ingeniería', 'Devuelve la cotangente de un número complejo.'],
  'IMCSC': ['Ingeniería', 'Devuelve la cosecante de un número complejo.'],
  'IMCSCH': ['Ingeniería', 'Devuelve la cosecante hiperbólica de un número complejo.'],
  'IMSEC': ['Ingeniería', 'Devuelve la secante de un número complejo.'],
  'IMSECH': ['Ingeniería', 'Devuelve la secante hiperbólica de un número complejo.'],
  'IMSINH': ['Ingeniería', 'Devuelve el seno hiperbólico de un número complejo.'],
  'IMTAN': ['Ingeniería', 'Devuelve la tangente de un número complejo.'],
  'OCT.A.BIN': ['Ingeniería', 'Convierte un número octal en binario.'],
  'OCT.A.DEC': ['Ingeniería', 'Convierte un número octal en decimal.'],
  'OCT.A.HEX': ['Ingeniería', 'Convierte un número octal en hexadecimal.'],

  // ===== Base de datos =====
  'BDCONTAR': ['Base de datos', 'Cuenta el número de celdas que contienen números en una base de datos.'],
  'BDCONTARA': ['Base de datos', 'Cuenta el número de celdas no vacías en una base de datos.'],
  'BDDESVEST': ['Base de datos', 'Calcula la desviación estándar a partir de una muestra de entradas seleccionadas.'],
  'BDDESVESTP': ['Base de datos', 'Calcula la desviación estándar de la población total de las entradas seleccionadas.'],
  'BDEXTRAER': ['Base de datos', 'Extrae de una base de datos un único registro que cumple los criterios especificados.'],
  'BDMAX': ['Base de datos', 'Devuelve el valor máximo de las entradas seleccionadas de la base de datos.'],
  'BDMIN': ['Base de datos', 'Devuelve el valor mínimo de las entradas seleccionadas de la base de datos.'],
  'BDPRODUCTO': ['Base de datos', 'Multiplica los valores de un campo de registros que cumplen los criterios.'],
  'BDPROMEDIO': ['Base de datos', 'Devuelve el promedio de las entradas seleccionadas en la base de datos.'],
  'BDSUMA': ['Base de datos', 'Suma los números de la columna de campo de los registros que cumplen los criterios.'],
  'BDVAR': ['Base de datos', 'Calcula la varianza a partir de una muestra de entradas seleccionadas.'],
  'BDVARP': ['Base de datos', 'Calcula la varianza a partir de la población total de entradas seleccionadas.'],

  // ===== Matrices =====
  'ARRAYFORMULA': ['Matrices', 'Habilita el cálculo de matriz de la expresión.'],
  'ARRAY_CONSTRAIN': ['Matrices', 'Restringe el tamaño del resultado de una matriz.'],
  'MAXPOOL': ['Matrices', 'Reduce una matriz tomando el valor máximo de cada bloque.'],
  'MEDIANPOOL': ['Matrices', 'Reduce una matriz tomando la mediana de cada bloque.']
};

const FX_CATEGORIAS = [
  'Matemáticas y trigonometría', 'Estadística', 'Texto', 'Lógica', 'Fecha y hora',
  'Búsqueda y referencia', 'Finanzas', 'Ingeniería', 'Información', 'Base de datos', 'Matrices', 'Otras'
];
